/**
 * Provision the untouched SciFact development split used by the V2 external
 * evaluation. Inputs are fetched from a commit-pinned public mirror and are
 * accepted only when their SHA-256 matches the values frozen in the protocol.
 * The data directory is gitignored; no benchmark examples are edited or
 * generated by this script.
 */
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';

const MIRROR_COMMIT = '051b5245aa9d4b98c1302920cc5e4958b9e30ef9';
const MIRROR_ROOT = `https://raw.githubusercontent.com/vidi-deshp12/scifact-claim-verification/${MIRROR_COMMIT}/data`;
const TARGET_DIR = path.join(process.cwd(), 'data', 'external', 'scifact');

const FILES = [
  {
    name: 'claims_dev.jsonl',
    sha256: '86f0435d08fdb65d1aa41d1472684f57e6e71930626497bdf4d7a9ec1a632217'
  },
  {
    name: 'corpus.jsonl',
    sha256: 'b8d6c89624cb2ed74dee8938effc4f5d8bd2086887880af8110d64be4ceade62'
  }
] as const;

function hash(data: Buffer): string {
  return crypto.createHash('sha256').update(data).digest('hex');
}

async function main(): Promise<void> {
  fs.mkdirSync(TARGET_DIR, { recursive: true });
  console.log('TruthLens V2 external data — SciFact dev (untouched)');
  console.log(`Pinned mirror commit: ${MIRROR_COMMIT}`);

  for (const file of FILES) {
    const target = path.join(TARGET_DIR, file.name);
    if (fs.existsSync(target)) {
      const existing = fs.readFileSync(target);
      const digest = hash(existing);
      if (digest === file.sha256) {
        console.log(`  OK ${file.name}: existing file matches ${digest}`);
        continue;
      }
      throw new Error(
        `${target} exists but SHA-256=${digest}, expected ${file.sha256}. ` +
        'Refusing to overwrite an unrecognized benchmark file.'
      );
    }

    const url = `${MIRROR_ROOT}/${file.name}`;
    console.log(`  fetching ${url}`);
    const response = await fetch(url, {
      redirect: 'follow',
      signal: AbortSignal.timeout(180_000),
      headers: { 'User-Agent': 'truthlens-v2-external-evaluation' }
    });
    if (!response.ok) throw new Error(`HTTP ${response.status} ${response.statusText} for ${url}`);
    const data = Buffer.from(await response.arrayBuffer());
    const digest = hash(data);
    if (digest !== file.sha256) {
      throw new Error(`${file.name}: SHA-256=${digest}, expected frozen ${file.sha256}; file rejected.`);
    }
    fs.writeFileSync(target, data);
    console.log(`  OK ${file.name}: wrote ${data.length} bytes, SHA-256=${digest}`);
  }

  console.log('SciFact dev ready. No examples or labels were transformed.');
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
